title: "윤영준 - 전북대학교 컴퓨터인공지능학부"
baseURL: 'https://yangbun-GIT.github.io/'
theme: "wowchemy"

languages:
  ko:
    languageName: "한국어"
    weight: 1
    contentDir: "content/ko"

  en:
    languageName: "English"
    weight: 2
    contentDir: "content/en"

sitemap:
  changefreq: daily
  priority: 0.5
  filename: sitemap.xml
