# Configuration of Hugo
# Guide: https://docs.hugoblox.com/tutorial/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

title: YJY-Portfolio # Website name
baseURL: 'https://yangbun-GIT.github.io/' # Website URL

############################
## PAGE OPTIONS
############################

cascade:
  # Blog post options
  - _target:
      path: /post/**
    editable: true
    reading_time: true
    commentable: true
    show_related: true
    show_breadcrumb: true

############################
## LANGUAGE
############################

defaultContentLanguage: ko
hasCJKLanguage: false
defaultContentLanguageInSubdir: true #하위 디럭터리 사용
removePathAccents: true

############################
## Site header
############################

header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: true
    show_day_night: true
    show_search: true
    highlight_active_link: false
    logo:
      image: "/assets/images/logo.png"
      text: ""

############################
## footer
############################

footer:
  copyright:
    notice: '© {year} Me. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

############################
## ADVANCED
############################

enableGitInfo: false
summaryLength: 30
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  authors: '/author/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, JSON, WebAppManifest, headers, redirects]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 75
  anchor: smart
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  author: authors
markup:
  _merge: deep
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70
security:
  _merge: deep
sitemap:
  _merge: deep
minify:
  _merge: deep
