# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: 메인
    url: /
    weight: 10

  - name: 소개
    url: about/
    weight: 30

  #경력 메뉴 (부코)
  - name: 경력
    weight: 50

  #경력 하위 메뉴
  - name: 학습 교과
    parent: 경력
    url: language/
    weight: 55
    children:
      - name: 기계학습
        url: /language/Linux
        weight: 56
      - name: 데이터마이닝
        url: /language/C
        weight: 57
      - name: 초급프로젝트
        url: /language/Python
        weight: 58

  - name: 프로그래밍 언어
    parent: 경력
    url: language/
    weight: 60

  #프로젝트 메뉴 (부모)
  - name: 프로젝트
    weight: 70

  #프로젝트 하위 메뉴
  - name: 프로젝트1
    parent: 프로젝트
    url: /
    weight: 75
  - name: 프로젝트2
    parent: 프로젝트
    url: /
    weight: 80
  - name: 프로젝트3
    parent: 프로젝트
    url: /
    weight: 85

  - name: 연락처
    url: /contact
    weight: 90
