# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: 홈
    url: /
    weight: 10

  - name: 소개
    url: about/
    weight: 30

  #경력 메뉴 (부모) - 드롭다운
  - name: 경력
    weight: 50

  #경력 하위 메뉴
  - name: 학습
    parent: 경력
    url: class/
    weight: 55

  - name: 프로그래밍 언어
    parent: 경력
    url: language/
    weight: 60
    children:
      - name: 기계학습
        url: /language/Linux
        weight: 61
      - name: 데이터마이닝
        url: /language/C
        weight: 62
      - name: 초급프로젝트
        url: /language/Python
        weight: 63

  #프로젝트 메뉴 (부모)
  - name: 프로젝트
    url: project
    weight: 70
    children:
      #프로젝트 하위 메뉴
      - name: 리눅스-채팅 프로그램
        parent: 프로젝트
        url: /project/Chat
        weight: 75
      - name: 데이터베이스 설계
        parent: 프로젝트
        url: /project/Database
        weight: 80
      - name: 포트폴리오 제작
        parent: 프로젝트
        url: /project/Portfolio
        weight: 85

  - name: 연락처
    url: /contact
    weight: 90
